<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Draft_bi bi-plus ec-text-title hovercurso_be1925</name>
   <tag></tag>
   <elementGuidId>1d220ea2-6d8f-4d1a-80db-972b26c18634</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>form >> internal:has-text=&quot;Workflow IDDescriptionActiveDraft Draft Kosong Task Task Kosong&quot;i >> i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>71a4fcff-292e-499e-b112-91467d767822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>3291b1c6-1917-4520-8bee-7f91bd67aa0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#formModal</value>
      <webElementGuid>7ba7e063-53a8-4fa3-a1eb-912efc4d3a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bi bi-plus ec-text-title hover:cursor-pointer</value>
      <webElementGuid>74981f51-209f-4293-a2a9-a3e1eb35adec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;modal-open&quot;]/app-root[1]/app-pages[1]/main[@class=&quot;bg-primary-50&quot;]/div[@class=&quot;flex flex-wrap&quot;]/div[@class=&quot;bg-primary-50 w-5/6&quot;]/workflow-app-pages[1]/app-flow-process-form[1]/div[@class=&quot;m-7&quot;]/div[1]/div[@class=&quot;ec-card mb-3&quot;]/div[@class=&quot;ec-card-body&quot;]/div[@class=&quot;ec-card-content&quot;]/div[1]/form[@class=&quot;ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;grid grid-cols-2 gap-5 mb-3&quot;]/div[@class=&quot;col-span-1&quot;]/div[@class=&quot;ec-card border border-primary-500&quot;]/div[@class=&quot;bg-primary-500 ec-text-subtitle-2 text-neutral-50 px-3&quot;]/div[@class=&quot;flex justify-between align-middle&quot;]/i[@class=&quot;bi bi-plus ec-text-title hover:cursor-pointer&quot;]</value>
      <webElementGuid>cb0c3c5c-0982-47c5-ba02-7ec534ea41e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/i</value>
      <webElementGuid>3ffbdf02-45d8-4d20-b03f-d6e173998512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
