<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Workflow ID_workflowId</name>
   <tag></tag>
   <elementGuidId>45d605c8-80de-4e0f-94e4-2c49d3314515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#workflowId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='workflowId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Workflow ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d991ebd-147c-43dd-8562-75cdabd8dc0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>01c4d621-b802-4175-92eb-8b254c17bbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>workflowId</value>
      <webElementGuid>e90e52b6-4fe3-44fa-8b10-22364150ab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Workflow ID</value>
      <webElementGuid>49d7ebc0-4fb5-40a2-95df-3f8afd71e283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workflowId</value>
      <webElementGuid>ce58bdeb-d1f4-46f1-9a54-fda7bb703754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded w-full ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>6605e4bf-f88e-4d83-b7d8-127806947cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workflowId&quot;)</value>
      <webElementGuid>033f9d0f-6e2a-40aa-a176-68e25b93d190</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='workflowId']</value>
      <webElementGuid>15a591f8-b764-4240-b884-d8ff2e30d40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>8fe2edba-76e9-4699-8ef9-83b3e4cdbad2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'workflowId' and @placeholder = 'Workflow ID']</value>
      <webElementGuid>0b4b16eb-3c95-4edf-9f2a-f498a31d8ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
