<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Task ID_task_id</name>
   <tag></tag>
   <elementGuidId>cb1145e7-eefb-4b3c-b6e0-b2d31b5ab6f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='task_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Task ID&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f71ceda6-5fc9-46ee-b625-94e2a3cdbd56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>task_id</value>
      <webElementGuid>6b8f01f2-464b-4be6-9f7e-5effdb5e490f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f47f2243-cdd5-4366-b22b-25b6e24d392a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>task_id</value>
      <webElementGuid>3a31e886-b206-41a8-8463-d66c2da6700a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Task ID</value>
      <webElementGuid>caa2d7b3-9106-42cc-8486-13351eb15015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>taskId</value>
      <webElementGuid>9192f928-ea06-4549-aa0a-9960592f47a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>bd319f82-3dce-4bcc-b58d-3a28b903564d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task_id&quot;)</value>
      <webElementGuid>ffa670a3-e675-41dd-984c-b6f91c89a444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='task_id']</value>
      <webElementGuid>cd5d04d1-a300-4371-838a-bd69b9c73c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formModal']/div/div/form/div/div[2]/div[2]/input</value>
      <webElementGuid>5594a340-4ee9-433e-a492-f43ce999cd30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>dbd7c06f-2d9b-434f-8813-fc7918b0084e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'task_id' and @type = 'text' and @id = 'task_id' and @placeholder = 'Task ID']</value>
      <webElementGuid>dbff67ec-d142-461a-8db4-08eef632ce53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
