<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flow Process_inputFlow</name>
   <tag></tag>
   <elementGuidId>e92e9ee8-7e3b-4a24-b951-9e962c905918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFlow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFlow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Workflow ID, Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fea172ff-108a-49ef-aa3c-595542f2b2a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c457b1a-631b-4d17-b504-881ffe1ddcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFlow</value>
      <webElementGuid>d5e35811-f94b-40be-8313-072d663ad8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Workflow ID, Description</value>
      <webElementGuid>626f9dc5-7835-4fc5-987d-5a4eef0c063f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workflowId</value>
      <webElementGuid>8599d879-d08e-4b09-a165-4949a29da35e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded w-full ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c6573300-64ca-4d4c-90f0-03ff6f41f0e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFlow&quot;)</value>
      <webElementGuid>840f6477-7593-48e7-a5f1-47b04006755c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFlow']</value>
      <webElementGuid>9af20ae7-3fbb-4070-a95c-df72853519b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>614fba16-5550-41c8-9a2c-2794a5d2976f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputFlow' and @placeholder = 'Workflow ID, Description']</value>
      <webElementGuid>995c91fb-e8a4-4977-90dd-62b2d04a3775</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
