<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Flow Process_inputFlow</name>
   <tag></tag>
   <elementGuidId>faee3548-39b0-4547-a547-86284c6b082f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputFlow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputFlow']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Workflow ID, Description&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37f41032-d6cf-45df-ab6f-0745c4085feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6fea3df1-289a-480b-9b04-7a924b56c8b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputFlow</value>
      <webElementGuid>6e4d8315-c0fd-451e-bb6f-84777f2c009e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Workflow ID, Description</value>
      <webElementGuid>49b27ced-35e5-4578-97ed-c69dfc7a9cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>workflowId</value>
      <webElementGuid>10e1971f-d560-4728-bc60-9ac9d51eb650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ec-form-control-rounded w-full ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f55fd9ad-124b-4a52-8aa0-ebd223322356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputFlow&quot;)</value>
      <webElementGuid>8aeb2ca6-ad49-411c-aad3-409a29deba8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputFlow']</value>
      <webElementGuid>8a57a434-9679-46ae-a419-6fd6cc45c55b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>c4865db8-9704-42b2-95a3-d9ee2b8ae6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputFlow' and @placeholder = 'Workflow ID, Description']</value>
      <webElementGuid>dea8bdb9-6a95-4ef7-bee9-e566311ab263</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
